[package]
name = "rstun"
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
rustls = { version = "0.20", features = ["dangerous_configuration", "quic"] }
clap = { version = "3.0.7", features = ["derive"] }
rcgen = "0.10"
tokio = { version = "1.21", features = ["full"] }
pretty_env_logger = "0.4.0"
ring = "0.16.20"
log = "0.4"
chrono = "0.4"
anyhow = "1.0"
quinn = "0.9.3"
quinn-proto = "0.9.2"
futures-util = "0.3"
bincode = "1.3.3"
pin-utils = "0.1.0"
enum-as-inner = "0.5"
num_cpus = "1.13.1"
rs-utilities = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustls-platform-verifier = { git = "https://github.com/neevek/rustls-platform-verifier" }
byte-pool = { git = "https://github.com/neevek/byte-pool" }
x509-parser = "0.15"
lazy_static = "1.4"

[dev-dependencies]
jni = "0.19"
android_logger = "0.11"

[target.aarch64-linux-android.dependencies]
jni = "0.19"
android_logger = "0.11"

[target.armv7-linux-androideabi.dependencies]
jni = "0.19"
android_logger = "0.11"

[profile.release]
opt-level = "z"
strip = true
lto = "fat"
panic = "abort"
